# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48f27a538fb8a668ae26d700cdea3531fd1968cec7c217564ec952c361e59af62b83f60297a47c2fbe6b819938463e6145dd4c05626b7a5beaaf27a73fa40d26

test:
  secret_key_base: 603d93aacf334167691f6be3263b50f2a4bfce0b9db1305be6adf91b9a66d45a6e049b6de9b39c66237bcd4ca16fb26260a9af402666ad231356f8c547d10681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
